language: node_js
node_js:
  - "lts/*" # Latest LTS version of NodeJs
notifications:
  email:
    on_success: always
    on_failure: always
install:
  - npm install
script: # test build (Continuous Integration)
  - npm run build
  - npm run test
cache: # Retrieve modules from cache and update when something changes
  directories:
    - "node_modules"
